openapi: 3.0.3
info:
  title: Inditex GFT API
  description: Inditex technical test API
  version: 1.0.0
servers:
  - url: http://localhost:8080
tags:
  - name: prices
    description: Price for products
paths:
  /prices/v1:
    summary: nosti
    $ref: v1/prices/prices.yaml
components:
  schemas:
    PriceControllerModel:
      $ref: v1/prices/priceControllerModel.yaml